### ISSUE TITLE
ARQ implementation doesn't conform to existing RQ functionality

### ISSUE THREAD

**Issue by Acedus** [kubevirt/application-aware-quota#78]
**What happened**:
Tried using an ARQ the same way as a RQ for schedulable resources (CPU/RAM) and tried creating Pods with no resource specification (i.e. no `cpu.requests`).

Using a vanilla RQ, the creation request would fail with the following error:
```
is forbidden: failed quota: ...: must specify requests.cpu for: test-creation-rq; 
```

Using ARQ, the creation request is admitted and proceeds to usage evaluation (gating) before being promptly admitted if there are sufficient resources in the quota.

**What you expected to happen**:
ARQ should still conform to the RQ implementation constraints despite [being recognized by the community as a mistake](https://github.com/kubernetes/kubernetes/blob/master/pkg/quota/v1/evaluator/core/pods.go#L89) to preserve transitional compatibility (personally I rely on RQ admission to enforce resource specification instead of LimitRanges and other admission controllers).

**How to reproduce it (as minimally and precisely as possible)**:
Create any Pod / Pod controller without specifying resources.

**Comment by Acedus** [comment]
P.S. not sure about this being a bug (it isn't), rather a design decision that I disagree with.

**Comment by Barakmor1** [comment]
@Acedus Yes indeed that was a design decision as mentioned [here](https://github.com/kubevirt/application-aware-quota/blob/e72e988ec98aa78cff1e7668af8ef0f36f38b6df/pkg/aaq-controller/aaq-evaluator/aaq-evaluator.go#L39).

The decision was made based on the following user story:

```
Creating non-guaranteed QoS pods in a multi-tenant cluster

As a user in a multi-tenant Kubernetes cluster, I need to deploy best-effort pods for low-priority 
workloads, which should utilize spare cluster resources and be the first to terminate during shortages. 
However, there’s a catch: my namespace has a ResourceQuota enforced by the cluster administrator. 
Currently, this quota might restrict the creation of pods that do not specify `requests.cpu`, `limits.cpu`, 
`requests.memory`, or `limits.memory`. This limitation prevents the deployment of best-effort pods and 
certain burstable pods in my namespace.
```

This user story is described in the [documentation PR](https://github.com/kubevirt/application-aware-quota/pull/74), which is a work in progress.

Also, please note that [Kubernetes behavior is not consistent across different resources.](https://github.com/kubernetes/kubernetes/issues/110956)

**Comment by Acedus** [comment]
@Barakmor1 thanks for the clarification.
While I do understand the rationale behind this decision and the corresponding user stories, it still doesn't address my specific issue. 

What is recommended for users that do not care for best-effort Pods and want strict enforcement of schedulable resources in conjunction with an ARQ? Would a LimitRange be required as is the standard practice for other resources that aren't enforced such as ephemeral storage?

**Comment by Barakmor1** [comment]
> @Barakmor1 thanks for the clarification. While I do understand the rationale behind this decision and the corresponding user stories, it still doesn't address my specific issue.
> 
> What is recommended for users that do not care for best-effort Pods and want strict enforcement of schedulable resources in conjunction with an ARQ? Would a LimitRange be required as is the standard practice for other resources that aren't enforced such as ephemeral storage?

The recommendation would indeed be to create LimitRange, as also suggested by the sig-node team of Kubernetes [here](https://github.com/kubernetes/kubernetes/issues/110956#issuecomment-1212209388)

Thank you for bringing this up. I'll ensure to include this information in the documentation PR. Please let me know if there's anything else on your mind.

**Comment by Acedus** [comment]
Thanks for the quick response, I'll be closing this issue now.
